apiVersion: v1
kind: Service
metadata:
  name: authnusers-q-service
  namespace: dev
  labels:
    app: authnusers-q
spec:
  type: LoadBalancer
  selector:
    app: authnusers-q
    color: blue  # Inicialmente aponta para blue. Será alterado via kubectl patch durante o deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  sessionAffinity: ClientIP  # Mantém sessões durante o switch
