apiVersion: apps/v1
kind: Deployment
metadata:
  name: lendings-c-canary
  namespace: dev
  labels:
    app: lendings-c
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lendings-c
      version: canary
  template:
    metadata:
      labels:
        app: lendings-c
        version: canary
    spec:
      containers:
        - name: lendings-c
          image: {{IMAGE_CANARY}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8881
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"