apiVersion: v1
kind: Service
metadata:
  name: reader_q-service
  namespace: dev
  labels:
    app: reader_q
spec:
  type: LoadBalancer
  selector:
    app: reader_q
    color: blue  # Inicialmente aponta para blue. Será alterado via kubectl patch durante o deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  sessionAffinity: ClientIP  # Mantém sessões durante o switch
